### ISSUE TITLE
download_data issue

### ISSUE THREAD

**Issue by zackarno** [ElliottMess/koboAPI#7]
Hi Elliot, 

This package is great! I'm not sure if you are still working on it at the moment, but I could not get a bunch of functions to work properly. The issues I found were usually due to object and function names being overwritten. I have fixed the package to work for my needs in my forked repo. It now works for the simple cases of downloading all the forms in a kobo account into a table, downloading a kobo dataset, and downloading the XLSForm form. The changes I made may have broken the some of the stuff for more complex use-cases where you want to deal with languages differently or extract the repeat groups into a nested list column. Therefore, it may not make sense for me to submit a pull request yet. However, let me know your thoughts. Thanks!

I also added a standardize_form function in kobo_utils to be used after download_form. It just puts the columns back to how they would have been when the form was downloaded (just fixes list_name in survey dataframe). I made the function separate because I didn't want to change columns that might be crucial for other functionality. In this standard format kobold functions (seths package) can be used which are quite convenient. If making this standardization can be done inside the download_form function without breaking other processes that would be simpler.

**Comment by ElliottMess** [comment]
Hey @zackarno,

Sorry, for the very late response, I just picked up the development of this package again after 2 years. I revamped the whole package to improve the structure the package and implement best practices in package development.

The issue that you were facing in the most simple way should have been fixed. I will have a look at your fork and specifically the `standardize_form` to link up to a more proper output format.

**Comment by zackarno** [comment]
Hi @ElliottMess ,

no worries, i think i messed around on my fork for a specific project and was able to get it to do what I needed. However, if I were you I wouldn't spend any time looking at my fork, because any changes that I made were very "patchy/hacky" and I stopped developing or using it a long time ago.

If you have not seen this yet, I think it might be worth the checking out the [robotoolbox package](https://github.com/dickoa/robotoolbox).  I haven't used it yet, but it looks like there has been some work dedicated to this since you were last developing the `KoboAPI` package

**Comment by ElliottMess** [comment]
Thanks @zackarno , I have missed [robotoolbox ](https://github.com/dickoa/robotoolbox) , I will have a look but it looks like a more featureful version of the my new release. I will see if I then retire this package and contribute to robotoolbox.

**Comment by zackarno** [comment]
cool! curious to see how it goes!
