### ISSUE TITLE
Problem to download data

### ISSUE THREAD

**Issue by zxrey** [ElliottMess/koboAPI#8]
When I try to download my data i found this problem in this function:

download_data : function (formid, user, pwd, api = "https://kobo.humanitarianresponse.info", seperator = "\\/")
download_data("841767", "xxxxx", "xxxxx", api = "https://kobo.humanitarianresponse.info", seperator = "\\/")

 |============================================================================| 100%
Error in new2old_id(formid, download_forms_all) : 
  all_forms must be a dataframe

**Comment by ElliottMess** [comment]
Hi @zxrey ,

Thanks for reporting the bug, and deepest apologies for not replying earlier. I had put the development of this package on the side for a while.

I hope that the new version of the package solves your problem, even if it might break your scripts by renaming the function.
